#Question:

Write a Python notebook that generates a file containing the following data:

Email addresses. Must have an "@"
Phone numbers
Home Address
Person's name
Year born. Use realistic values.
Number of kids. Use realistic values.
Categorical variable: rent or own?
Annual income. Optional challenge: Use a non-uniform distribution
Number of speeding tickets in past year. Optional challenge: Use a non-uniform distribution
The user of your notebook should be able to specify how many entities are to be generated.

â€‹Do not include the .csv output file in your submission -- the file should be generated dynamically.

Order of columns in CSV is not relevant.

I referred this link http://listofrandomnames.com/index.cfm?generated to get the list of random names.

http://effbot.org/pyfaq/how-do-i-delete-a-file-and-other-file-questions.htm. I used this link to check the available data after deleting the unwanted data.

I stored the randomly selected names in "n_list.txt" file.

In [1]:
import random
import numpy
import csv
from random import randint
import os
from os import path
if(path.exists("fakedata.csv")):
    os.remove("fakedata.csv")
nameslist=open("n_list.txt","r")
n_list=nameslist.read()

For creating mail ID's,I stored few domain names.

In [2]:
n_list=n_list.split()
domain_list=["gmail.com","twitter.com","ben.edu","umbc.edu","google.co.in"]

Below is to check whether the house is owned or rental

In [3]:
housestatus=["own","rent"]

To generate the address,this is the link I referred for the states information and stored as USA states.txt.http://www.softschools.com/social_studies/state_abbreviations/

Here, I defined the address function in which I took zipcode as zipcd,flat number,country and state.

In [4]:
def address():
    zipcd=str(randint(10000,99999))
    states=open("USA states.txt","r")
    states_list=states.read().split("\n")
    flatnum=str(randint(100,500))
    address1="flat num"+" "+str(flatnum)+" "+str(random.choice(states_list))+" "+"USA"+zipcd
    return(address1)

Here I took random function to generate random information and referred this code.https://www.geeksforgeeks.org/random-numbers-in-python/
I choosed name variable in which two names are selected from the n_list and stored.
To generate email ID, I choosed replace function to remove space between two names from domain_list and replaced with '@'
I stored numbers between(1000000000,9999999999) using randint function in the variable phonenumber.
Choosed years randomly from (1950,2000) and stored in variable year.
choosing randomly from the list housestatus which I stored previously.
choosing randomly a number in between (100000-1000000) using the randint function to generate annual income.
Randomly choosing a number in between (0-10) using randint function.
Here I am storing all the above in a list i.e.,completedata.

In [5]:
completedata=[]
for i in range(100):
    name=random.choice(n_list)+" "+random.choice(n_list)
    email=str(name.replace(" "," "))+"@"+random.choice(domain_list)
    phonenumber=str(randint(1000000000,9999999999))
    year=str(randint(1950,2010))
    kids=str(randint(0,4))
    h_status=random.choice(housestatus)
    dinfo=[]
    dinfo.append(' '.join(email))
    dinfo.append(phonenumber)
    dinfo.append(address())
    dinfo.append(name)
    dinfo.append(year)
    dinfo.append(kids)
    dinfo.append(h_status)
    dinfo.append(randint(100000,1000000))
    dinfo.append(randint(0,10))
    completedata.append(dinfo)

In [6]:
completedata

[['P l u d e   E l l i @ t w i t t e r . c o m',
  '6454237499',
  'flat num 374 Tennessee - TN USA64715',
  'Plude Elli',
  '1991',
  '0',
  'own',
  322550,
  7],
 ['B u r r i e r   B o y d e n @ g o o g l e . c o . i n',
  '9798813559',
  'flat num 448 Mississippi - MS USA98379',
  'Burrier Boyden',
  '1988',
  '1',
  'own',
  931190,
  2],
 ['S u d i e   A l y c e @ g o o g l e . c o . i n',
  '8515148655',
  'flat num 143 Connecticut - CT USA96225',
  'Sudie Alyce',
  '1973',
  '3',
  'rent',
  532512,
  6],
 ['B a n g s   S h i z u k o @ t w i t t e r . c o m',
  '8253810463',
  'flat num 112 Michigan - MI USA60324',
  'Bangs Shizuko',
  '2007',
  '4',
  'rent',
  299465,
  2],
 ['J a n e e   V a n i t a @ t w i t t e r . c o m',
  '1194193427',
  'flat num 276 Louisiana - LA USA46077',
  'Janee Vanita',
  '1973',
  '0',
  'own',
  360940,
  4],
 ['T a n a   A d e l a i d a @ g m a i l . c o m',
  '5346993975',
  'flat num 114 Mississippi - MS USA49760',
  'Tana Adelaida',
  '2009',
  '0',
  'own',
  916974,
  10],
 ['S h i z u k o   G r a c i e l a @ u m b c . e d u',
  '3299252352',
  'flat num 132 Virginia - VA USA16896',
  'Shizuko Graciela',
  '1955',
  '0',
  'rent',
  515875,
  8],
 ['K i n c h   S w e a r e n g i n @ u m b c . e d u',
  '7732956912',
  'flat num 219 Kentucky - KY USA72004',
  'Kinch Swearengin',
  '1985',
  '2',
  'rent',
  633766,
  0],
 ['D a m e w o o d   T h i e l e @ u m b c . e d u',
  '7553203189',
  'flat num 378 Montana - MT USA57691',
  'Damewood Thiele',
  '1996',
  '3',
  'own',
  937589,
  5],
 ['G r a c i e l a   L a u n a @ u m b c . e d u',
  '9392014862',
  'flat num 289 Arkansas - AR USA69868',
  'Graciela Launa',
  '1995',
  '1',
  'own',
  603808,
  3],
 ['A d e l a i d a   C l e m e n t i n e @ u m b c . e d u',
  '7853637913',
  'flat num 226 Connecticut - CT USA12893',
  'Adelaida Clementine',
  '1979',
  '3',
  'own',
  191021,
  1],
 ['D e l a h a n t y   G r a c i e l a @ t w i t t e r . c o m',
  '2649211612',
  'flat num 105 Minnesota - MN USA81264',
  'Delahanty Graciela',
  '2002',
  '0',
  'rent',
  756893,
  4],
 ['J a n e e   B u r r i e r @ g o o g l e . c o . i n',
  '3596484335',
  'flat num 491 Texas - TX USA30614',
  'Janee Burrier',
  '2002',
  '1',
  'rent',
  855542,
  8],
 ['F r a n   V a n i t a @ g o o g l e . c o . i n',
  '5311704291',
  'flat num 236 Massachusetts - MA USA43949',
  'Fran Vanita',
  '1994',
  '1',
  'own',
  681885,
  4],
 ['L u m s d e n   L u m s d e n @ t w i t t e r . c o m',
  '6762199847',
  'flat num 230 Tennessee - TN USA33614',
  'Lumsden Lumsden',
  '2009',
  '1',
  'own',
  106533,
  5],
 ['V a n i t a   S u d i e @ g o o g l e . c o . i n',
  '9001560954',
  'flat num 431 Maryland - MD USA79028',
  'Vanita Sudie',
  '1977',
  '1',
  'own',
  576418,
  3],
 ['L u m s d e n   L e v e r @ u m b c . e d u',
  '5541163336',
  'flat num 259 Delaware - DE USA81663',
  'Lumsden Lever',
  '1990',
  '3',
  'rent',
  150073,
  9],
 ['S w e a r e n g i n   J o n a h @ g o o g l e . c o . i n',
  '5629776258',
  'flat num 216 Delaware - DE USA43555',
  'Swearengin Jonah',
  '1972',
  '3',
  'own',
  672034,
  5],
 ['T a n a   B u r r i e r @ g m a i l . c o m',
  '4964457894',
  'flat num 483 Virginia - VA USA92836',
  'Tana Burrier',
  '2002',
  '3',
  'rent',
  821411,
  1],
 ['L a v o n a   S h i z u k o @ u m b c . e d u',
  '7128624000',
  'flat num 225 West Virginia - WV USA24025',
  'Lavona Shizuko',
  '1989',
  '3',
  'own',
  157437,
  8],
 ['C l a r i t a   D a n a @ b e n . e d u',
  '8271936008',
  'flat num 375 Utah - UT USA36588',
  'Clarita Dana',
  '1971',
  '1',
  'own',
  735207,
  9],
 ['L a u n a   B o y d e n @ b e n . e d u',
  '3592596982',
  'flat num 206 Ohio - OH USA47598',
  'Launa Boyden',
  '1974',
  '1',
  'own',
  208388,
  2],
 ['W o u l l a r d   F r a n @ g m a i l . c o m',
  '9046066763',
  'flat num 479 Arizona - AZ USA38466',
  'Woullard Fran',
  '1993',
  '4',
  'rent',
  786176,
  5],
 ['A d e l a i d a   P l u d e @ b e n . e d u',
  '9905886219',
  'flat num 103 New Mexico - NM USA62455',
  'Adelaida Plude',
  '1957',
  '3',
  'own',
  509674,
  9],
 ['D e s i r a e   D a n a @ t w i t t e r . c o m',
  '3618290864',
  'flat num 297 Alabama - AL USA84678',
  'Desirae Dana',
  '1975',
  '3',
  'rent',
  497984,
  6],
 ['A n i t a   M a t t o o n @ g o o g l e . c o . i n',
  '8963829953',
  'flat num 174 California - CA USA71511',
  'Anita Mattoon',
  '1957',
  '4',
  'own',
  974722,
  2],
 ['A d e l a i d a   L e v e r @ u m b c . e d u',
  '5799713690',
  'flat num 169 Iowa - IA USA98910',
  'Adelaida Lever',
  '1980',
  '0',
  'rent',
  758118,
  4],
 ['M a n i   L u m s d e n @ g m a i l . c o m',
  '7495462708',
  'flat num 406 Massachusetts - MA USA68224',
  'Mani Lumsden',
  '1959',
  '1',
  'rent',
  748718,
  0],
 ['R o s a m a r i a   D e l a h a n t y @ u m b c . e d u',
  '4716172677',
  'flat num 495 Rhode Island - RI USA34264',
  'Rosamaria Delahanty',
  '1965',
  '3',
  'rent',
  530444,
  9],
 ['R i g g e n b a c h   C a s s i d y @ u m b c . e d u',
  '5672644272',
  'flat num 321 Michigan - MI USA86992',
  'Riggenbach Cassidy',
  '1987',
  '0',
  'own',
  695346,
  10],
 ['D e l a h a n t y   L i n t z @ g o o g l e . c o . i n',
  '1375406390',
  'flat num 262 Georgia - GA USA44314',
  'Delahanty Lintz',
  '1987',
  '0',
  'rent',
  550134,
  9],
 ['F o b b s   M a l e n a @ u m b c . e d u',
  '9768040855',
  'flat num 183 South Carolina - SC USA64650',
  'Fobbs Malena',
  '2010',
  '0',
  'own',
  477717,
  2],
 ['V e n z o n   K i t c h i n @ t w i t t e r . c o m',
  '1342560596',
  'flat num 299 Nebraska - NE USA94651',
  'Venzon Kitchin',
  '1950',
  '3',
  'rent',
  746343,
  0],
 ['M a l e n a   D e s i r a e @ g m a i l . c o m',
  '5894677079',
  'flat num 330 West Virginia - WV USA72091',
  'Malena Desirae',
  '1979',
  '3',
  'rent',
  108202,
  1],
 ['V a n i t a   C a t e @ t w i t t e r . c o m',
  '5798216505',
  'flat num 392 Texas - TX USA42342',
  'Vanita Cate',
  '1997',
  '0',
  'own',
  684110,
  0],
 ['D a m e w o o d   W h e t s e l @ u m b c . e d u',
  '1233618472',
  'flat num 179 Delaware - DE USA35495',
  'Damewood Whetsel',
  '1983',
  '0',
  'rent',
  635035,
  10],
 ['A n i t a   L a u n a @ g m a i l . c o m',
  '3363102356',
  'flat num 411 North Carolina - NC USA40961',
  'Anita Launa',
  '1976',
  '4',
  'rent',
  911236,
  10],
 ['R i c k i e   L i n t z @ u m b c . e d u',
  '8768636117',
  'flat num 410 Rhode Island - RI USA54992',
  'Rickie Lintz',
  '1994',
  '2',
  'own',
  840764,
  3],
 ['F o b b s   G r a c i e l a @ u m b c . e d u',
  '7285770384',
  'flat num 436 New York - NY USA72991',
  'Fobbs Graciela',
  '1992',
  '2',
  'own',
  692752,
  5],
 ['C a r b o n a r o   L u m s d e n @ b e n . e d u',
  '4633794381',
  'flat num 412 Pennsylvania - PA USA67174',
  'Carbonaro Lumsden',
  '1998',
  '3',
  'own',
  504487,
  6],
 ['C a t e   T h i e l e @ b e n . e d u',
  '9101747161',
  'flat num 183 Pennsylvania - PA USA13051',
  'Cate Thiele',
  '1964',
  '0',
  'rent',
  945970,
  5],
 ['F o b b s   C l a r i t a @ u m b c . e d u',
  '8474795349',
  'flat num 420 Indiana - IN USA30584',
  'Fobbs Clarita',
  '1966',
  '3',
  'rent',
  245322,
  8],
 ['T r o w b r i d g e   V e n z o n @ u m b c . e d u',
  '4752880487',
  'flat num 330 Illinois - IL USA72772',
  'Trowbridge Venzon',
  '1996',
  '0',
  'own',
  455528,
  1],
 ['C a r r i e   R o s a m a r i a @ g o o g l e . c o . i n',
  '1287744262',
  'flat num 273 Washington - WA USA78311',
  'Carrie Rosamaria',
  '1971',
  '2',
  'own',
  279663,
  3],
 ['L a v o n a   A n i t a @ g m a i l . c o m',
  '7964077891',
  'flat num 299 Iowa - IA USA78043',
  'Lavona Anita',
  '2000',
  '2',
  'own',
  892914,
  10],
 ['C a r b o n a r o   R i c k i e @ u m b c . e d u',
  '3156496218',
  'flat num 420 Rhode Island - RI USA75462',
  'Carbonaro Rickie',
  '2007',
  '0',
  'rent',
  624252,
  8],
 ['B a n g s   S w e a r e n g i n @ b e n . e d u',
  '7783373985',
  'flat num 104 Indiana - IN USA60892',
  'Bangs Swearengin',
  '1986',
  '3',
  'own',
  613064,
  4],
 ['D e l a h a n t y   P l u d e @ u m b c . e d u',
  '7462843387',
  'flat num 211 Louisiana - LA USA94049',
  'Delahanty Plude',
  '2009',
  '1',
  'rent',
  665821,
  5],
 ['C l e m e n t i n e   V a n i t a @ u m b c . e d u',
  '9129205529',
  'flat num 447 Washington - WA USA91766',
  'Clementine Vanita',
  '1954',
  '3',
  'own',
  113511,
  0],
 ['D e l a h a n t y   L a u n a @ b e n . e d u',
  '5587665078',
  'flat num 326 West Virginia - WV USA76319',
  'Delahanty Launa',
  '1972',
  '3',
  'own',
  420470,
  4],
 ['A l y c e   C a t e @ g o o g l e . c o . i n',
  '1201228308',
  'flat num 325 Oregon - OR USA65516',
  'Alyce Cate',
  '1976',
  '2',
  'own',
  725432,
  4],
 ['L u t h y   S u d i e @ g m a i l . c o m',
  '1313030741',
  'flat num 456 Indiana - IN USA79638',
  'Luthy Sudie',
  '1962',
  '4',
  'rent',
  704885,
  8],
 ['B u r r i e r   C a r r i e @ g m a i l . c o m',
  '5640650681',
  'flat num 134 Indiana - IN USA28796',
  'Burrier Carrie',
  '2002',
  '3',
  'rent',
  612894,
  7],
 ['C a t e   M a d a l y n @ u m b c . e d u',
  '4233313307',
  'flat num 438 South Dakota - SD USA21563',
  'Cate Madalyn',
  '2006',
  '4',
  'rent',
  238817,
  7],
 ['M a t t o o n   L a u n a @ g m a i l . c o m',
  '2786783294',
  'flat num 300 Minnesota - MN USA57879',
  'Mattoon Launa',
  '1975',
  '2',
  'own',
  177880,
  1],
 ['C a s s i d y   B a n g s @ t w i t t e r . c o m',
  '2139660054',
  'flat num 360 West Virginia - WV USA54680',
  'Cassidy Bangs',
  '2010',
  '2',
  'own',
  623006,
  0],
 ['C a s s i d y   A d e l a i d a @ u m b c . e d u',
  '6910889718',
  'flat num 271 Texas - TX USA64064',
  'Cassidy Adelaida',
  '1991',
  '3',
  'rent',
  321984,
  2],
 ['B a i l e y   L a u n a @ g o o g l e . c o . i n',
  '9789670604',
  'flat num 218 New Jersey - NJ USA21736',
  'Bailey Launa',
  '1995',
  '0',
  'rent',
  172192,
  1],
 ['K i n c h   R o n i @ g m a i l . c o m',
  '1410361551',
  'flat num 399 Vermont - VT USA63233',
  'Kinch Roni',
  '2006',
  '0',
  'rent',
  652160,
  0],
 ['C l e m e n t i n e   W h e t s e l @ u m b c . e d u',
  '2145956894',
  'flat num 379 Delaware - DE USA51513',
  'Clementine Whetsel',
  '1956',
  '4',
  'own',
  140278,
  9],
 ['B o y d e n   K i n c h @ t w i t t e r . c o m',
  '5744551329',
  'flat num 292 Iowa - IA USA62947',
  'Boyden Kinch',
  '1957',
  '4',
  'own',
  228844,
  6],
 ['W e a t h e r w a x   T h i e l e @ u m b c . e d u',
  '7747922352',
  'flat num 340 Iowa - IA USA40078',
  'Weatherwax Thiele',
  '1967',
  '2',
  'rent',
  673394,
  6],
 ['G r a c i e l a   D i g e n n a r o @ b e n . e d u',
  '7181401727',
  'flat num 221 Washington - WA USA46044',
  'Graciela Digennaro',
  '2010',
  '2',
  'own',
  636358,
  4],
 ['B a i l e y   T a n a @ u m b c . e d u',
  '8268767381',
  'flat num 199 Virginia - VA USA98740',
  'Bailey Tana',
  '1972',
  '4',
  'rent',
  853896,
  7],
 ['E l i s e o   V e n z o n @ u m b c . e d u',
  '9936180175',
  'flat num 254 California - CA USA31518',
  'Eliseo Venzon',
  '1993',
  '2',
  'rent',
  432526,
  4],
 ['R o n i   K i t c h i n @ t w i t t e r . c o m',
  '4843556842',
  'flat num 190 Georgia - GA USA35257',
  'Roni Kitchin',
  '1995',
  '3',
  'own',
  781736,
  9],
 ['L i n t z   T h i e l e @ t w i t t e r . c o m',
  '2032642590',
  'flat num 235 Maine - ME USA92987',
  'Lintz Thiele',
  '1952',
  '4',
  'rent',
  587597,
  1],
 ['B a n g s   J a n e e @ b e n . e d u',
  '3585581838',
  'flat num 384 Alabama - AL USA34583',
  'Bangs Janee',
  '2008',
  '4',
  'rent',
  358729,
  7],
 ['T r o w b r i d g e   S u d i e @ g m a i l . c o m',
  '1173248093',
  'flat num 199 Washington - WA USA34896',
  'Trowbridge Sudie',
  '1961',
  '1',
  'own',
  143843,
  10],
 ['S h i z u k o   W o u l l a r d @ t w i t t e r . c o m',
  '1522415722',
  'flat num 226 Oregon - OR USA71981',
  'Shizuko Woullard',
  '1997',
  '0',
  'own',
  376897,
  3],
 ['M a d a l y n   S h i z u k o @ u m b c . e d u',
  '2299719667',
  'flat num 478 Utah - UT USA93502',
  'Madalyn Shizuko',
  '1982',
  '3',
  'rent',
  939797,
  4],
 ['D i g e n n a r o   D e l a h a n t y @ g o o g l e . c o . i n',
  '9164840839',
  'flat num 108 New Hampshire - NH USA71891',
  'Digennaro Delahanty',
  '1961',
  '3',
  'rent',
  700862,
  1],
 ['B u l a h   L a u n a @ t w i t t e r . c o m',
  '8006358770',
  'flat num 254 North Carolina - NC USA43981',
  'Bulah Launa',
  '1976',
  '1',
  'own',
  417481,
  5],
 ['L a g u a r d i a   A l y c e @ g o o g l e . c o . i n',
  '4488892228',
  'flat num 211 West Virginia - WV USA84829',
  'Laguardia Alyce',
  '1989',
  '4',
  'rent',
  227955,
  6],
 ['M a d a l y n   V e n z o n @ g o o g l e . c o . i n',
  '6534924391',
  'flat num 437 Arkansas - AR USA47718',
  'Madalyn Venzon',
  '1988',
  '0',
  'rent',
  770789,
  5],
 ['T a n a   E f f i e @ b e n . e d u',
  '6404528890',
  'flat num 206 Michigan - MI USA72966',
  'Tana Effie',
  '1997',
  '0',
  'rent',
  964634,
  7],
 ['C a t e   B a n g s @ g m a i l . c o m',
  '9466140890',
  'flat num 499 Wisconsin - WI USA17460',
  'Cate Bangs',
  '1996',
  '0',
  'own',
  343286,
  2],
 ['G r a c i e l a   W o u l l a r d @ b e n . e d u',
  '1524132569',
  'flat num 283 Alabama - AL USA33459',
  'Graciela Woullard',
  '1955',
  '4',
  'own',
  747258,
  6],
 ['M a l e n a   A n i t a @ t w i t t e r . c o m',
  '8931905365',
  'flat num 350 Mississippi - MS USA65585',
  'Malena Anita',
  '1971',
  '1',
  'rent',
  869227,
  10],
 ['D e s i r a e   D e s i r a e @ g o o g l e . c o . i n',
  '2290483483',
  'flat num 424 Virginia - VA USA71675',
  'Desirae Desirae',
  '2004',
  '0',
  'own',
  610723,
  3],
 ['M a t t o o n   C a t e @ g m a i l . c o m',
  '8415036781',
  'flat num 454 Illinois - IL USA72724',
  'Mattoon Cate',
  '1952',
  '0',
  'rent',
  182466,
  8],
 ['T h i e l e   C a s s i d y @ t w i t t e r . c o m',
  '5367804216',
  'flat num 201 New Jersey - NJ USA31749',
  'Thiele Cassidy',
  '1971',
  '3',
  'own',
  550313,
  8],
 ['C a r r i e   R o n i @ b e n . e d u',
  '6541216070',
  'flat num 373 Ohio - OH USA70177',
  'Carrie Roni',
  '1952',
  '1',
  'own',
  587961,
  6],
 ['L i n t z   C a r r i e @ g o o g l e . c o . i n',
  '4116891010',
  'flat num 129 Oklahoma - OK USA60114',
  'Lintz Carrie',
  '1983',
  '1',
  'rent',
  465275,
  2],
 ['B a l c h   C a s s i d y @ g o o g l e . c o . i n',
  '5913787759',
  'flat num 238 Illinois - IL USA86297',
  'Balch Cassidy',
  '1999',
  '4',
  'rent',
  472670,
  3],
 ['K i n c h   S h i z u k o @ g m a i l . c o m',
  '8277319889',
  'flat num 129 Indiana - IN USA33424',
  'Kinch Shizuko',
  '2000',
  '0',
  'rent',
  736871,
  4],
 ['B a n g s   W o u l l a r d @ u m b c . e d u',
  '8969890301',
  'flat num 149 Alaska - AK USA90366',
  'Bangs Woullard',
  '2002',
  '3',
  'rent',
  594927,
  9],
 ['B a n g s   L a u n a @ b e n . e d u',
  '2897325740',
  'flat num 284 Delaware - DE USA38867',
  'Bangs Launa',
  '1969',
  '2',
  'rent',
  929135,
  10],
 ['J a n e e   V e n z o n @ t w i t t e r . c o m',
  '9947506927',
  'flat num 472 Nevada - NV USA69684',
  'Janee Venzon',
  '1970',
  '4',
  'own',
  760750,
  10],
 ['K a r o l y n   S h i z u k o @ u m b c . e d u',
  '5455142819',
  'flat num 389 Pennsylvania - PA USA49385',
  'Karolyn Shizuko',
  '1984',
  '2',
  'own',
  644445,
  3],
 ['B a i l e y   L a u n a @ t w i t t e r . c o m',
  '1458608672',
  'flat num 256 Indiana - IN USA63507',
  'Bailey Launa',
  '1950',
  '0',
  'own',
  926911,
  2],
 ['G r a c i e l a   R i c k i e @ b e n . e d u',
  '3839029450',
  'flat num 165 South Dakota - SD USA59765',
  'Graciela Rickie',
  '1957',
  '1',
  'own',
  442011,
  1],
 ['T h i e l e   S w e a r e n g i n @ g o o g l e . c o . i n',
  '8116192741',
  'flat num 382 Oregon - OR USA47488',
  'Thiele Swearengin',
  '1963',
  '1',
  'own',
  747522,
  7],
 ['D a n a   B o y d e n @ b e n . e d u',
  '2117226270',
  'flat num 147 Wyoming - WY USA93799',
  'Dana Boyden',
  '1978',
  '0',
  'rent',
  185840,
  6],
 ['S u d i e   B u r r i e r @ t w i t t e r . c o m',
  '5704554748',
  'flat num 439 Maine - ME USA49166',
  'Sudie Burrier',
  '2007',
  '1',
  'own',
  574457,
  10],
 ['K i t c h i n   R o s a m a r i a @ u m b c . e d u',
  '8161615175',
  'flat num 375 Rhode Island - RI USA47187',
  'Kitchin Rosamaria',
  '1992',
  '4',
  'own',
  695076,
  9],
 ['A n i t a   M a l e n a @ g o o g l e . c o . i n',
  '7711853417',
  'flat num 201 New Mexico - NM USA65590',
  'Anita Malena',
  '1965',
  '0',
  'own',
  183434,
  2],
 ['G r a c i e l a   M a l e n a @ u m b c . e d u',
  '7071486091',
  'flat num 314 South Dakota - SD USA59523',
  'Graciela Malena',
  '1954',
  '4',
  'rent',
  316650,
  5],
 ['D i g e n n a r o   B u l a h @ g m a i l . c o m',
  '8119739370',
  'flat num 275 Illinois - IL USA94627',
  'Digennaro Bulah',
  '1965',
  '1',
  'rent',
  965795,
  1],
 ['W h e t s e l   V a n i t a @ u m b c . e d u',
  '9373882700',
  'flat num 151 New Mexico - NM USA53649',
  'Whetsel Vanita',
  '1988',
  '4',
  'rent',
  630570,
  1]]

Now I am converting the list "completedata" into dataframe "df"

In [7]:
import pandas as pd
df=pd.DataFrame(completedata)
df

,0,1,2,3,4,5,6,7,8
0,P l u d e E l l i @ t w i t t e r . c o m,6454237499,flat num 374 Tennessee - TN USA64715,Plude Elli,1991,0,own,322550,7
1,B u r r i e r B o y d e n @ g o o g l e . c ...,9798813559,flat num 448 Mississippi - MS USA98379,Burrier Boyden,1988,1,own,931190,2
2,S u d i e A l y c e @ g o o g l e . c o . i n,8515148655,flat num 143 Connecticut - CT USA96225,Sudie Alyce,1973,3,rent,532512,6
3,B a n g s S h i z u k o @ t w i t t e r . c o m,8253810463,flat num 112 Michigan - MI USA60324,Bangs Shizuko,2007,4,rent,299465,2
4,J a n e e V a n i t a @ t w i t t e r . c o m,1194193427,flat num 276 Louisiana - LA USA46077,Janee Vanita,1973,0,own,360940,4
5,T a n a A d e l a i d a @ g m a i l . c o m,5346993975,flat num 114 Mississippi - MS USA49760,Tana Adelaida,2009,0,own,916974,10
6,S h i z u k o G r a c i e l a @ u m b c . e d u,3299252352,flat num 132 Virginia - VA USA16896,Shizuko Graciela,1955,0,rent,515875,8
7,K i n c h S w e a r e n g i n @ u m b c . e d u,7732956912,flat num 219 Kentucky - KY USA72004,Kinch Swearengin,1985,2,rent,633766,0
8,D a m e w o o d T h i e l e @ u m b c . e d u,7553203189,flat num 378 Montana - MT USA57691,Damewood Thiele,1996,3,own,937589,5
9,G r a c i e l a L a u n a @ u m b c . e d u,9392014862,flat num 289 Arkansas - AR USA69868,Graciela Launa,1995,1,own,603808,3
10,A d e l a i d a C l e m e n t i n e @ u m b ...,7853637913,flat num 226 Connecticut - CT USA12893,Adelaida Clementine,1979,3,own,191021,1
11,D e l a h a n t y G r a c i e l a @ t w i t ...,2649211612,flat num 105 Minnesota - MN USA81264,Delahanty Graciela,2002,0,rent,756893,4
12,J a n e e B u r r i e r @ g o o g l e . c o ...,3596484335,flat num 491 Texas - TX USA30614,Janee Burrier,2002,1,rent,855542,8
13,F r a n V a n i t a @ g o o g l e . c o . i n,5311704291,flat num 236 Massachusetts - MA USA43949,Fran Vanita,1994,1,own,681885,4
14,L u m s d e n L u m s d e n @ t w i t t e r ...,6762199847,flat num 230 Tennessee - TN USA33614,Lumsden Lumsden,2009,1,own,106533,5
15,V a n i t a S u d i e @ g o o g l e . c o . i n,9001560954,flat num 431 Maryland - MD USA79028,Vanita Sudie,1977,1,own,576418,3
16,L u m s d e n L e v e r @ u m b c . e d u,5541163336,flat num 259 Delaware - DE USA81663,Lumsden Lever,1990,3,rent,150073,9
17,S w e a r e n g i n J o n a h @ g o o g l e ...,5629776258,flat num 216 Delaware - DE USA43555,Swearengin Jonah,1972,3,own,672034,5
18,T a n a B u r r i e r @ g m a i l . c o m,4964457894,flat num 483 Virginia - VA USA92836,Tana Burrier,2002,3,rent,821411,1
19,L a v o n a S h i z u k o @ u m b c . e d u,7128624000,flat num 225 West Virginia - WV USA24025,Lavona Shizuko,1989,3,own,157437,8
20,C l a r i t a D a n a @ b e n . e d u,8271936008,flat num 375 Utah - UT USA36588,Clarita Dana,1971,1,own,735207,9
21,L a u n a B o y d e n @ b e n . e d u,3592596982,flat num 206 Ohio - OH USA47598,Launa Boyden,1974,1,own,208388,2
22,W o u l l a r d F r a n @ g m a i l . c o m,9046066763,flat num 479 Arizona - AZ USA38466,Woullard Fran,1993,4,rent,786176,5
23,A d e l a i d a P l u d e @ b e n . e d u,9905886219,flat num 103 New Mexico - NM USA62455,Adelaida Plude,1957,3,own,509674,9
24,D e s i r a e D a n a @ t w i t t e r . c o m,3618290864,flat num 297 Alabama - AL USA84678,Desirae Dana,1975,3,rent,497984,6
25,A n i t a M a t t o o n @ g o o g l e . c o ...,8963829953,flat num 174 California - CA USA71511,Anita Mattoon,1957,4,own,974722,2
26,A d e l a i d a L e v e r @ u m b c . e d u,5799713690,flat num 169 Iowa - IA USA98910,Adelaida Lever,1980,0,rent,758118,4
27,M a n i L u m s d e n @ g m a i l . c o m,7495462708,flat num 406 Massachusetts - MA USA68224,Mani Lumsden,1959,1,rent,748718,0
28,R o s a m a r i a D e l a h a n t y @ u m b ...,4716172677,flat num 495 Rhode Island - RI USA34264,Rosamaria Delahanty,1965,3,rent,530444,9
29,R i g g e n b a c h C a s s i d y @ u m b c ...,5672644272,flat num 321 Michigan - MI USA86992,Riggenbach Cassidy,1987,0,own,695346,10
...,...,...,...,...,...,...,...,...,...
70,M a d a l y n S h i z u k o @ u m b c . e d u,2299719667,flat num 478 Utah - UT USA93502,Madalyn Shizuko,1982,3,rent,939797,4
71,D i g e n n a r o D e l a h a n t y @ g o o ...,9164840839,flat num 108 New Hampshire - NH USA71891,Digennaro Delahanty,1961,3,rent,700862,1
72,B u l a h L a u n a @ t w i t t e r . c o m,8006358770,flat num 254 North Carolina - NC USA43981,Bulah Launa,1976,1,own,417481,5
73,L a g u a r d i a A l y c e @ g o o g l e . ...,4488892228,flat num 211 West Virginia - WV USA84829,Laguardia Alyce,1989,4,rent,227955,6
74,M a d a l y n V e n z o n @ g o o g l e . c ...,6534924391,flat num 437 Arkansas - AR USA47718,Madalyn Venzon,1988,0,rent,770789,5
75,T a n a E f f i e @ b e n . e d u,6404528890,flat num 206 Michigan - MI USA72966,Tana Effie,1997,0,rent,964634,7
76,C a t e B a n g s @ g m a i l . c o m,9466140890,flat num 499 Wisconsin - WI USA17460,Cate Bangs,1996,0,own,343286,2
77,G r a c i e l a W o u l l a r d @ b e n . e d u,1524132569,flat num 283 Alabama - AL USA33459,Graciela Woullard,1955,4,own,747258,6
78,M a l e n a A n i t a @ t w i t t e r . c o m,8931905365,flat num 350 Mississippi - MS USA65585,Malena Anita,1971,1,rent,869227,10
79,D e s i r a e D e s i r a e @ g o o g l e . ...,2290483483,flat num 424 Virginia - VA USA71675,Desirae Desirae,2004,0,own,610723,3
80,M a t t o o n C a t e @ g m a i l . c o m,8415036781,flat num 454 Illinois - IL USA72724,Mattoon Cate,1952,0,rent,182466,8
81,T h i e l e C a s s i d y @ t w i t t e r . ...,5367804216,flat num 201 New Jersey - NJ USA31749,Thiele Cassidy,1971,3,own,550313,8
82,C a r r i e R o n i @ b e n . e d u,6541216070,flat num 373 Ohio - OH USA70177,Carrie Roni,1952,1,own,587961,6
83,L i n t z C a r r i e @ g o o g l e . c o . i n,4116891010,flat num 129 Oklahoma - OK USA60114,Lintz Carrie,1983,1,rent,465275,2
84,B a l c h C a s s i d y @ g o o g l e . c o ...,5913787759,flat num 238 Illinois - IL USA86297,Balch Cassidy,1999,4,rent,472670,3
85,K i n c h S h i z u k o @ g m a i l . c o m,8277319889,flat num 129 Indiana - IN USA33424,Kinch Shizuko,2000,0,rent,736871,4
86,B a n g s W o u l l a r d @ u m b c . e d u,8969890301,flat num 149 Alaska - AK USA90366,Bangs Woullard,2002,3,rent,594927,9
87,B a n g s L a u n a @ b e n . e d u,2897325740,flat num 284 Delaware - DE USA38867,Bangs Launa,1969,2,rent,929135,10
88,J a n e e V e n z o n @ t w i t t e r . c o m,9947506927,flat num 472 Nevada - NV USA69684,Janee Venzon,1970,4,own,760750,10
89,K a r o l y n S h i z u k o @ u m b c . e d u,5455142819,flat num 389 Pennsylvania - PA USA49385,Karolyn Shizuko,1984,2,own,644445,3
90,B a i l e y L a u n a @ t w i t t e r . c o m,1458608672,flat num 256 Indiana - IN USA63507,Bailey Launa,1950,0,own,926911,2
91,G r a c i e l a R i c k i e @ b e n . e d u,3839029450,flat num 165 South Dakota - SD USA59765,Graciela Rickie,1957,1,own,442011,1
92,T h i e l e S w e a r e n g i n @ g o o g l ...,8116192741,flat num 382 Oregon - OR USA47488,Thiele Swearengin,1963,1,own,747522,7
93,D a n a B o y d e n @ b e n . e d u,2117226270,flat num 147 Wyoming - WY USA93799,Dana Boyden,1978,0,rent,185840,6
94,S u d i e B u r r i e r @ t w i t t e r . c o m,5704554748,flat num 439 Maine - ME USA49166,Sudie Burrier,2007,1,own,574457,10
95,K i t c h i n R o s a m a r i a @ u m b c . ...,8161615175,flat num 375 Rhode Island - RI USA47187,Kitchin Rosamaria,1992,4,own,695076,9
96,A n i t a M a l e n a @ g o o g l e . c o . i n,7711853417,flat num 201 New Mexico - NM USA65590,Anita Malena,1965,0,own,183434,2
97,G r a c i e l a M a l e n a @ u m b c . e d u,7071486091,flat num 314 South Dakota - SD USA59523,Graciela Malena,1954,4,rent,316650,5
98,D i g e n n a r o B u l a h @ g m a i l . c o m,8119739370,flat num 275 Illinois - IL USA94627,Digennaro Bulah,1965,1,rent,965795,1
99,W h e t s e l V a n i t a @ u m b c . e d u,9373882700,flat num 151 New Mexico - NM USA53649,Whetsel Vanita,1988,4,rent,630570,1

Referred this link to convert columns names to data frames.https://r.789695.n4.nabble.com/To-give-column-names-of-a-data-frame-td2249996.html

Store the data frame into csv file f_data.csv

In [8]:
df.columns=['Email','Phone number','Home Address','Persons name','Year born','Number of Kids','House status','Annual Income','No of Speeding Tickets in last year']
df.to_csv("f_data.csv")